/**
 * Omnichannel API
 * This is the beta version of Omnichannel API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: admin@messente.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SMS', 'model/Scenarios', 'model/Viber'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SMS'), require('./Scenarios'), require('./Viber'));
  } else {
    // Browser globals (root is window)
    if (!root.OmnichannelApi) {
      root.OmnichannelApi = {};
    }
    root.OmnichannelApi.Omnimessage = factory(root.OmnichannelApi.ApiClient, root.OmnichannelApi.SMS, root.OmnichannelApi.Scenarios, root.OmnichannelApi.Viber);
  }
}(this, function(ApiClient, SMS, Scenarios, Viber) {
  'use strict';




  /**
   * The Omnimessage model module.
   * @module model/Omnimessage
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Omnimessage</code>.
   * @alias module:model/Omnimessage
   * @class
   * @param scenarios {module:model/Scenarios} 
   * @param to {String} Phone number of the recipient in international number format
   */
  var exports = function(scenarios, to) {
    var _this = this;

    _this['scenarios'] = scenarios;


    _this['to'] = to;

  };

  /**
   * Constructs a <code>Omnimessage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Omnimessage} obj Optional instance to populate.
   * @return {module:model/Omnimessage} The populated <code>Omnimessage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('scenarios')) {
        obj['scenarios'] = Scenarios.constructFromObject(data['scenarios']);
      }
      if (data.hasOwnProperty('viber')) {
        obj['viber'] = Viber.constructFromObject(data['viber']);
      }
      if (data.hasOwnProperty('sms')) {
        obj['sms'] = SMS.constructFromObject(data['sms']);
      }
      if (data.hasOwnProperty('to')) {
        obj['to'] = ApiClient.convertToType(data['to'], 'String');
      }
      if (data.hasOwnProperty('drl_url')) {
        obj['drl_url'] = ApiClient.convertToType(data['drl_url'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Scenarios} scenarios
   */
  exports.prototype['scenarios'] = undefined;
  /**
   * Viber message content
   * @member {module:model/Viber} viber
   */
  exports.prototype['viber'] = undefined;
  /**
   * SMS message content
   * @member {module:model/SMS} sms
   */
  exports.prototype['sms'] = undefined;
  /**
   * Phone number of the recipient in international number format
   * @member {String} to
   */
  exports.prototype['to'] = undefined;
  /**
   * URL where the delivery report will be sent
   * @member {String} drl_url
   */
  exports.prototype['drl_url'] = undefined;



  return exports;
}));


