/**
 * Omnichannel API
 * This is the beta version of Omnichannel API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@messente.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OmnichannelApi) {
      root.OmnichannelApi = {};
    }
    root.OmnichannelApi.ScenarioItem = factory(root.OmnichannelApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ScenarioItem model module.
   * @module model/ScenarioItem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ScenarioItem</code>.
   * @alias module:model/ScenarioItem
   * @class
   * @param channel {module:model/ScenarioItem.ChannelEnum} 
   */
  var exports = function(channel) {
    var _this = this;

    _this['channel'] = channel;

  };

  /**
   * Constructs a <code>ScenarioItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ScenarioItem} obj Optional instance to populate.
   * @return {module:model/ScenarioItem} The populated <code>ScenarioItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('channel')) {
        obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
      }
      if (data.hasOwnProperty('validity')) {
        obj['validity'] = ApiClient.convertToType(data['validity'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ScenarioItem.ChannelEnum} channel
   */
  exports.prototype['channel'] = undefined;
  /**
   * @member {Number} validity
   */
  exports.prototype['validity'] = undefined;


  /**
   * Allowed values for the <code>channel</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ChannelEnum = {
    /**
     * value: "viber"
     * @const
     */
    "viber": "viber",
    /**
     * value: "sms"
     * @const
     */
    "sms": "sms"  };


  return exports;
}));


