/**
 * Omnichannel API
 * Messente's API which allows sending messages via various channels with fallback options.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Message'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Message'));
  } else {
    // Browser globals (root is window)
    if (!root.OmnichannelApi) {
      root.OmnichannelApi = {};
    }
    root.OmnichannelApi.Viber = factory(root.OmnichannelApi.ApiClient, root.OmnichannelApi.Message);
  }
}(this, function(ApiClient, Message) {
  'use strict';




  /**
   * The Viber model module.
   * @module model/Viber
   * @version 0.0.2
   */

  /**
   * Constructs a new <code>Viber</code>.
   * @alias module:model/Viber
   * @class
   * @extends module:model/Message
   * @implements module:model/Message
   * @param channel {} 
   */
  var exports = function(channel) {
    var _this = this;
    Message.call(_this, channel);
    Message.call(_this, channel);
    _this['channel'] = "viber";



  };

  /**
   * Constructs a <code>Viber</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Viber} obj Optional instance to populate.
   * @return {module:model/Viber} The populated <code>Viber</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      Message.constructFromObject(data, obj);
      Message.constructFromObject(data, obj);
      if (data.hasOwnProperty('text')) {
        obj['text'] = ApiClient.convertToType(data['text'], 'String');
      }
      if (data.hasOwnProperty('image_url')) {
        obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
      }
      if (data.hasOwnProperty('button_url')) {
        obj['button_url'] = ApiClient.convertToType(data['button_url'], 'String');
      }
      if (data.hasOwnProperty('button_text')) {
        obj['button_text'] = ApiClient.convertToType(data['button_text'], 'String');
      }
    }
    return obj;
  }

  exports.prototype = Object.create(Message.prototype);
  exports.prototype.constructor = exports;

  /**
   * Plaintext content for Viber
   * @member {String} text
   */
  exports.prototype['text'] = undefined;
  /**
   * URL for the embedded image. Valid combinations: 1) 'image_url' 2) 'text', 'image_url', 'button_url', 'button_text'
   * @member {String} image_url
   */
  exports.prototype['image_url'] = undefined;
  /**
   * URL of the button, must be specified along with 'text', 'button_text'  and 'image_url' (optional)
   * @member {String} button_url
   */
  exports.prototype['button_url'] = undefined;
  /**
   * Must be specified along with 'text', 'button_url', 'button_text', 'image_url' (optional)
   * @member {String} button_text
   */
  exports.prototype['button_text'] = undefined;

  // Implement Message interface:
  /**
   * @member {String} channel
   */
exports.prototype['channel'] = undefined;

  /**
   * Phone number or alphanumeric sender name
   * @member {String} sender
   */
exports.prototype['sender'] = undefined;

  /**
   * After how many minutes this channel is considered as failed and the next channel is attempted
   * @member {Number} validity
   */
exports.prototype['validity'] = undefined;



  return exports;
}));


