/**
 * Omnichannel API
 * This is the beta version of Omnichannel API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: admin@messente.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OmnichannelApi) {
      root.OmnichannelApi = {};
    }
    root.OmnichannelApi.Viber = factory(root.OmnichannelApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Viber model module.
   * @module model/Viber
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Viber</code>.
   * @alias module:model/Viber
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>Viber</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Viber} obj Optional instance to populate.
   * @return {module:model/Viber} The populated <code>Viber</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('text')) {
        obj['text'] = ApiClient.convertToType(data['text'], 'String');
      }
      if (data.hasOwnProperty('image_url')) {
        obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
      }
      if (data.hasOwnProperty('button_url')) {
        obj['button_url'] = ApiClient.convertToType(data['button_url'], 'String');
      }
      if (data.hasOwnProperty('button_text')) {
        obj['button_text'] = ApiClient.convertToType(data['button_text'], 'String');
      }
      if (data.hasOwnProperty('sender')) {
        obj['sender'] = ApiClient.convertToType(data['sender'], 'String');
      }
    }
    return obj;
  }

  /**
   * Plaintext content for Viber
   * @member {String} text
   */
  exports.prototype['text'] = undefined;
  /**
   * URL for the embedded image. Valid combinations: 1) 'image_url' 2) 'text', 'image_url', 'button_url', 'button_text'
   * @member {String} image_url
   */
  exports.prototype['image_url'] = undefined;
  /**
   * URL of the button, must be specified along with 'text', 'button_text'  and 'image_url' (optional)
   * @member {String} button_url
   */
  exports.prototype['button_url'] = undefined;
  /**
   * Must be specified along with 'text', 'button_url', 'button_text', 'image_url' (optional)
   * @member {String} button_text
   */
  exports.prototype['button_text'] = undefined;
  /**
   * Phone number or alphanumeric sender name
   * @member {String} sender
   */
  exports.prototype['sender'] = undefined;



  return exports;
}));


