/**
 * Omnichannel API
 * This is the beta version of Omnichannel API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@messente.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OmnichannelApi);
  }
}(this, function(expect, OmnichannelApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OmnichannelApi.Omnimessage();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Omnimessage', function() {
    it('should create an instance of Omnimessage', function() {
      // uncomment below and update the code to test Omnimessage
      //var instane = new OmnichannelApi.Omnimessage();
      //expect(instance).to.be.a(OmnichannelApi.Omnimessage);
    });

    it('should have the property scenarios (base name: "scenarios")', function() {
      // uncomment below and update the code to test the property scenarios
      //var instane = new OmnichannelApi.Omnimessage();
      //expect(instance).to.be();
    });

    it('should have the property viber (base name: "viber")', function() {
      // uncomment below and update the code to test the property viber
      //var instane = new OmnichannelApi.Omnimessage();
      //expect(instance).to.be();
    });

    it('should have the property sms (base name: "sms")', function() {
      // uncomment below and update the code to test the property sms
      //var instane = new OmnichannelApi.Omnimessage();
      //expect(instance).to.be();
    });

    it('should have the property to (base name: "to")', function() {
      // uncomment below and update the code to test the property to
      //var instane = new OmnichannelApi.Omnimessage();
      //expect(instance).to.be();
    });

    it('should have the property drlUrl (base name: "drl_url")', function() {
      // uncomment below and update the code to test the property drlUrl
      //var instane = new OmnichannelApi.Omnimessage();
      //expect(instance).to.be();
    });

    it('should have the property timeToSend (base name: "time_to_send")', function() {
      // uncomment below and update the code to test the property timeToSend
      //var instane = new OmnichannelApi.Omnimessage();
      //expect(instance).to.be();
    });

  });

}));
