/**
 * Omnichannel API
 * This is the beta version of Omnichannel API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@messente.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OmnichannelApi);
  }
}(this, function(expect, OmnichannelApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OmnichannelApi.SMS();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SMS', function() {
    it('should create an instance of SMS', function() {
      // uncomment below and update the code to test SMS
      //var instane = new OmnichannelApi.SMS();
      //expect(instance).to.be.a(OmnichannelApi.SMS);
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instane = new OmnichannelApi.SMS();
      //expect(instance).to.be();
    });

    it('should have the property sender (base name: "sender")', function() {
      // uncomment below and update the code to test the property sender
      //var instane = new OmnichannelApi.SMS();
      //expect(instance).to.be();
    });

    it('should have the property autoconvert (base name: "autoconvert")', function() {
      // uncomment below and update the code to test the property autoconvert
      //var instane = new OmnichannelApi.SMS();
      //expect(instance).to.be();
    });

    it('should have the property udh (base name: "udh")', function() {
      // uncomment below and update the code to test the property udh
      //var instane = new OmnichannelApi.SMS();
      //expect(instance).to.be();
    });

  });

}));
